include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  bind-hostname = "0.0.0.0"
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  aegis-events {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = aegis-events-dlq
      maxReceiveCount = 5
    }
  }

  aegis-events-dlq {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
